name: uk_bank_holidays
description: "Dart package for interacting with UK Government's Bank Holiday's API"
version: 0.0.1
repository: https://github.com/LucasBourne/uk_bank_holidays

environment:
  sdk: ^3.7.2

dependencies:
  build_runner: ^2.4.15
  collection: ^1.19.1
  dio: ^5.8.0+1
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
